#Import all required libraries
import pyqrcode
import png
from pyqrcode import QRCode

#your website or webpage to which we want to create QRCODE
s = "https://www.example.com/"

#STEP 1:crete url for the given webpage by using pyqrcode module
url = pyqrcode.create(s)

#STEP 2:svg will create XML file
********************SVG stands for Scalable Vector Graphics SVG is used to define graphics for the Web*********************************
url.svg("my.svg",scale=8)

# STEP 3:save your QRCODE which is generated by using PNG module in python
url.png("myqrcode.png",scale=10)
